### ISSUE TITLE
re configure ADF in AWS organization

### ISSUE THREAD

**Issue by 20FS21** [awslabs/aws-deployment-framework#439]
Hello team,
 for some problem i start re configure ADF in AWS organization that already exist.
I delete cloud formation in master account with the name serverlessrepo-aws-deployment-framework and in deployment account i delete all CF stack in the region.
Now when i rung the SAR ( ADF ....) and re deploy the stack in Master account my pipeline failed and give me the follow error:
![image](https://user-images.githubusercontent.com/77515163/154621627-801d2840-ea3e-4777-a9bd-8c395046ad11.png)
How can i fix it?
How can i re deploy ADF in my infrastructure without issues?
Thanks a lot

**Comment by 20FS21** [comment]
Team do you have some suggestion about this request?
Thanks a lot

**Comment by stemons** [comment]
Hello, could you please update the requirements.txt file in adf-build (aws-deployment-framework-bootstrap repository) to mirror the current version in master (https://github.com/awslabs/aws-deployment-framework/blob/master/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/requirements.txt).
This should fix the issue.

The updated content should be 

```
# Install libs here that you might want in AWS CodeBuild (On Master Account)
astroid~=2.9.0
aws-sam-cli==1.36.0
awscli==1.22.26
boto3==1.20.26
botocore==1.23.26
mock~=4.0.3
pip~=21.3.1
pylint~=2.12.2
pytest~=6.2.5
pyyaml>=5.4.1
six~=1.16.0
tenacity==8.0.1
urllib3~=1.26.7
```

**Comment by 20FS21** [comment]
Thanks a lot now i have this issue :
<img width="987" alt="image" src="https://user-images.githubusercontent.com/77515163/154964098-b9cd459e-e461-4f62-80f4-21e75bc245d4.png">

**Comment by 20FS21** [comment]
[stemons](https://github.com/stemons) the issue is very big for you? do you have some suggestion please for fix it. I used ADF in production and now i'm bloc :-(

**Comment by Mavrikios777** [comment]
Hello, I have a similar issue in deployment and cannot figure how to procede with it

**Comment by DeborohNoah** [comment]
I have a similar issue too,  been trying for days now but I still can't figure it out

**Comment by 20FS21** [comment]
hello team sorry that i disturb you but some from from developer team can help me to fix this issue that block me please?
Thanks a lot.

**Comment by 20FS21** [comment]
Hello team i fixed the issue delete from parameter groups the deployment account value. 
But now when I run [aws-deployment-framework-bootstrap] in my master account the deploy  of cloud formation in may deployment account failed with this error:

<img width="832" alt="image" src="https://user-images.githubusercontent.com/77515163/155260222-28448b8e-52ce-41d4-b655-e3f85595478b.png">

Could you help me to fix this?
thanks,

**Comment by 20FS21** [comment]
and in step function i have this error 
[ERROR] StateMachineDoesNotExist: An error occurred (StateMachineDoesNotExist) when calling the StartExecution operation: State Machine Does Not Exist: 'arn:aws:states:eu-west-1:xxxxxxxxxx:stateMachine:EnableCrossAccountAccess'
Traceback (most recent call last):
  File "/var/task/generic_account_config.py", line 40, in lambda_handler
    step_functions.execute_statemachine()
  File "/opt/python/stepfunctions.py", line 48, in execute_statemachine
    self._start_statemachine()
  File "/opt/python/stepfunctions.py", line 55, in _start_statemachine
    self.execution_arn = self.client.start_execution(
  File "/var/runtime/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)

**Comment by StewartW** [comment]
It looks like there's an issue with the initial commit handler in your master account. 
Let me look and see what can be done.

**Comment by 20FS21** [comment]
I must share with you some more info from my master account... I don't understand

**Comment by StewartW** [comment]
@20FS21  Sorry. I meant I was looking into a solution for you. 
If you checkout the v3.1.2 tag locally and then update the 
Jinja2 requirement to 3.0.3 in ```src/lambda_codebase/initial_commit/requirements.txt ```

You can then deploy this by using the AWS SAM CLI. 
You can start by packaging 
```
cd src
sam build
```
This will package the build artifacts in .aws-sam/build 

You can then deploy by using those artifacts or the SAM CLI. 

To use the SAM CLI 
```
sam deploy --guided --capabilities CAPABILITY_NAMED_IAM
```

This will give you a step-by-step guide on what parameters to pass in. Use the exact same values that you would for deploying from the SAR.

**Comment by 20FS21** [comment]
Jinja2~=3.0.3
boto3==1.14.63
cfn-custom-resource~=1.0.1

correct?

**Comment by StewartW** [comment]
That looks good to me

**Comment by 20FS21** [comment]
error again :-(
![image](https://user-images.githubusercontent.com/77515163/155298895-b8ce5b97-0e60-45c4-9204-c3ca5d237450.png)

**Comment by whysi** [comment]
Hi,
I'm facing a similar problem and I can see the same error that @20FS21 had.

![image](https://user-images.githubusercontent.com/93594835/155306349-d4935f72-3496-4f9a-a6ea-4641e902b227.png)

The issue seems related to:
https://github.com/aws/aws-sam-cli/issues/3661

`Received response status [FAILED] from custom resource. Message returned: cannot import name 'soft_unicode' from 'markupsafe' (/var/task/markupsafe/__init__.py) (RequestId: 9425c7ae-971a-4bdf-b3fc-db9779561bf0)`

I've already tried with adding to requirements.txt:
```
aws-sam-cli==1.38.1
markupsafe==2.0.1
```

but nothing changes.
I've just installed ADF, configured deployment account and OU (the first automated commit failed but we fixed it updating the requirements.txt as suggested on another recent issue here on github) and then tried to add another account in the organization with the bootstrap method (failed with the clouformation stack error that I've pasted before).

Thanks for your help.

**Comment by StewartW** [comment]
> [ERROR] Exception: State Machine on Deployment account XXXXXXXXXXXXhas status: FAILED, see logs Traceback (most recent call last):   File "/var/task/generic_account_config.py", line 40, in lambda_handler     step_functions.execute_statemachine()   File "/opt/python/stepfunctions.py", line 49, in execute_statemachine     self._wait_state_machine_execution()   File "/opt/python/stepfunctions.py", line 104, in _wait_state_machine_execution     raise Exception(

What error does the state machine have now, that it's created?

**Comment by 20FS21** [comment]
correct

**Comment by 20FS21** [comment]
fixed i bring deployment account our from ou and re put it in ou again and now it works perfectly 
Thanks
